language: java
jdk: oraclejdk8
# we use this distro to avoid issue when installing oraclejdk8
dist: trusty
cache:
 directories:
   - $HOME/.m2
before_deploy:
  - mvn --batch-mode versions:set -DnewVersion=${TRAVIS_TAG:1} --settings .travis/settings.xml
  - mvn clean package -DskipTests --settings .travis/settings.xml
deploy:
  provider: script
  script: bash .travis/maven-central-deploy.sh
  skip_cleanup: true
  on:
    tags: true